name: Update Profile Projects

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test updater
        run: |
          python --version
          ls -la
          ls -la .github/scripts
